const animeCatalog = [
  {
    title: "Fullmetal Alchemist: Brotherhood",
    genre: "Action, Adventure",
    studio: "Bones",
    rating: 9.2,
    year: 2009,
    image: "images/fullmetal.jpg",
    description:
      "Two brothers seek the Philosopher's Stone after a failed alchemy experiment.",
  },
  {
    title: "Attack on Titan",
    genre: "Action, Drama",
    studio: "Wit Studio / MAPPA",
    rating: 9.1,
    year: 2013,
    image: "images/aot.webp",
    description:
      "Humans fight for survival against towering man-eating titans.",
  },
  {
    title: "Bleach",
    genre: "Action, Supernatural",
    studio: "Studio Pierrot",
    rating: 8.6,
    year: 2004,
    image: "images/bleach.jpg",
    description: "A teen gains Soul Reaper powers and battles evil spirits.",
  },
  {
    title: "One Piece",
    genre: "Adventure, Fantasy",
    studio: "Toei Animation",
    rating: 8.8,
    year: 1999,
    image: "images/onepiece.jpg",
    description:
      "Luffy sails the seas with his crew to find the legendary treasure.",
  },
  {
    title: "Vinland Saga",
    genre: "Action, Drama",
    studio: "Wit Studio",
    rating: 8.8,
    year: 2019,
    image: "images/vinland.jpg",
    description: "A young warrior seeks revenge during the Viking era.",
  },
  {
    title: "Demon Slayer",
    genre: "Action, Supernatural",
    studio: "ufotable",
    rating: 8.5,
    year: 2019,
    image: "images/demonslayer.jpg",
    description: "A boy joins a demon-slaying corps to avenge his family.",
  },
  {
    title: "Death Note",
    genre: "Mystery, Supernatural",
    studio: "Madhouse",
    rating: 8.6,
    year: 2006,
    image: "images/deathnote.jpg",
    description: "A high schooler gains a deadly notebook and plays god.",
  },
  {
    title: "Jujutsu Kaisen",
    genre: "Action, Fantasy",
    studio: "MAPPA",
    rating: 8.7,
    year: 2020,
    image: "images/jjk.webp",
    description: "A student battles cursed spirits with supernatural powers.",
  },
  {
    title: "My Hero Academia",
    genre: "Action, Superhero",
    studio: "Bones",
    rating: 8.0,
    year: 2016,
    image: "images/mha.jpg",
    description: "A quirkless boy trains to become the greatest hero.",
  },
  {
    title: "Hunter x Hunter",
    genre: "Adventure, Fantasy",
    studio: "Madhouse",
    rating: 8.9,
    year: 2011,
    image: "images/hxh.jpg",
    description: "Gon seeks his father and faces deadly trials as a Hunter.",
  },
  {
    title: "Mob Psycho 100",
    genre: "Action, Comedy",
    studio: "Bones",
    rating: 8.7,
    year: 2016,
    image: "images/mob.jpg",
    description: "A powerful psychic boy tries to live a normal life.",
  },
  {
    title: "One Punch Man",
    genre: "Action, Comedy",
    studio: "Madhouse",
    rating: 8.5,
    year: 2015,
    image: "images/onepunch.jpg",
    description:
      "A hero defeats enemies with a single punch—and is bored by it.",
  },
  {
    title: "JoJo's Bizarre Adventure",
    genre: "Action, Adventure",
    studio: "David Production",
    rating: 8.8,
    year: 2012,
    image: "images/jojos.jpg",
    description: "Generations of Joestars battle supernatural foes in style.",
  },
  {
    title: "Tokyo Ghoul",
    genre: "Horror, Supernatural",
    studio: "Pierrot",
    rating: 7.9,
    year: 2014,
    image: "images/tokyo.jpg",
    description:
      "A college student becomes half-ghoul and fights for identity.",
  },
  {
    title: "Naruto",
    genre: "Adventure, Ninja",
    studio: "Pierrot",
    rating: 8.3,
    year: 2002,
    image: "images/naruto.jpg",
    description: "An outcast ninja dreams of becoming the Hokage.",
  },
  {
    title: "Cyberpunk: Edgerunners",
    genre: "Sci-Fi, Action",
    studio: "Trigger",
    rating: 8.5,
    year: 2022,
    image: "images/edgerunners.jpg",
    description:
      "A street kid becomes an Edgerunner in a tech-dystopian world.",
  },
  {
    title: "86",
    genre: "Sci-Fi, Drama",
    studio: "A-1 Pictures",
    rating: 8.3,
    year: 2021,
    image: "images/86.jpg",
    description:
      "A war is fought by unmanned drones—except they're not really unmanned.",
  },
  {
    title: "Re:Zero - Starting Life in Another World",
    genre: "Fantasy, Drama",
    studio: "White Fox",
    rating: 8.1,
    year: 2016,
    image: "images/rezero.jpg",
    description:
      "A boy is transported to a fantasy world and trapped in a time loop.",
  },
  {
    title: "Solo Leveling",
    genre: "Action, Fantasy",
    studio: "A-1 Pictures",
    rating: 8.7,
    year: 2024,
    image: "images/sololeveling.jpg",
    description:
      "A weak hunter becomes the world’s strongest through a system.",
  },
  {
    title: "Dandadan",
    genre: "Supernatural, Comedy",
    studio: "Science SARU",
    rating: 8.2,
    year: 2024,
    image: "images/dandadan.jpg",
    description:
      "Two teens dive into bizarre battles involving ghosts and aliens.",
  },
  {
    title: "Sakamoto Days",
    genre: "Action, Comedy",
    studio: "TMS Entertainment",
    rating: 8.3,
    year: 2025,
    image: "images/sakamoto.jpg",
    description:
      "A retired hitman turned family man is dragged back into action.",
  },
  {
    title: "Kaiju No. 8",
    genre: "Action, Sci-Fi",
    studio: "Production I.G",
    rating: 8.4,
    year: 2024,
    image: "images/kaiju8.jpg",
    description:
      "A monster cleanup worker gains kaiju powers and fights for humanity.",
  },
  {
    title: "Cowboy Bebop",
    genre: "Sci-Fi, Action",
    studio: "Sunrise",
    rating: 8.8,
    year: 1998,
    image: "images/cowboy.jpg",
    description: "Bounty hunters chase criminals across the galaxy in style.",
  },
  {
    title: "Code Geass",
    genre: "Mecha, Drama",
    studio: "Sunrise",
    rating: 8.9,
    year: 2006,
    image: "images/codegeass.jpg",
    description: "A prince with a mysterious power rebels against an empire.",
  },
  {
    title: "Steins;Gate",
    genre: "Sci-Fi, Thriller",
    studio: "White Fox",
    rating: 9.1,
    year: 2011,
    image: "images/steinsgate.jpg",
    description: "A scientist discovers time travel with dire consequences.",
  },
  {
    title: "Erased",
    genre: "Mystery, Drama",
    studio: "A-1 Pictures",
    rating: 8.5,
    year: 2016,
    image: "images/erased.jpg",
    description: "A man travels back in time to prevent a tragedy.",
  },
  {
    title: "Parasyte: The Maxim",
    genre: "Horror, Action",
    studio: "Madhouse",
    rating: 8.4,
    year: 2014,
    image: "images/parasyte.jpg",
    description: "A teen fights alien parasites that take over human bodies.",
  },
  {
    title: "Your Lie in April",
    genre: "Romance, Drama",
    studio: "A-1 Pictures",
    rating: 8.6,
    year: 2014,
    image: "images/yourlie.jpg",
    description: "A pianist rediscovers music and emotion through love.",
  },
  {
    title: "Toradora!",
    genre: "Romance, Comedy",
    studio: "J.C.Staff",
    rating: 8.0,
    year: 2008,
    image: "images/toradora.jpg",
    description: "Two classmates team up to help each other find love.",
  },
  {
    title: "The Promised Neverland",
    genre: "Mystery, Horror",
    studio: "CloverWorks",
    rating: 8.4,
    year: 2019,
    image: "images/neverland.jpg",
    description: "Children uncover a dark secret and plot their escape.",
  },
  {
    title: "Dr. Stone",
    genre: "Sci-Fi, Adventure",
    studio: "TMS Entertainment",
    rating: 8.2,
    year: 2019,
    image: "images/drstone.jpg",
    description:
      "A genius teen rebuilds civilization after humanity turns to stone.",
  },
  {
    title: "Black Clover",
    genre: "Fantasy, Action",
    studio: "Studio Pierrot",
    rating: 8.1,
    year: 2017,
    image: "images/blackclover.jpg",
    description: "A boy with no magic strives to become the Wizard King.",
  },
  {
    title: "Spy x Family",
    genre: "Comedy, Action",
    studio: "Wit Studio / CloverWorks",
    rating: 8.6,
    year: 2022,
    image: "images/spyxfamily.jpg",
    description: "A spy builds a fake family—unaware of their hidden talents.",
  },
];
