const animeCatalog = [
  {
    title: "Fullmetal Alchemist: Brotherhood",
    genre: "Action, Adventure",
    studio: "Bones",
    rating: 9.2,
    year: 2009,
    image: "images/fullmetal.jpg",
    description:
      "Two brothers seek the Philosopher's Stone after a failed alchemy experiment.",
  },
  {
    title: "Attack on Titan",
    genre: "Action, Drama",
    studio: "Wit Studio / MAPPA",
    rating: 9.1,
    year: 2013,
    image: "images/aot.webp",
    description:
      "Humans fight for survival against towering man-eating titans.",
  },
  {
    title: "Bleach",
    genre: "Action, Supernatural",
    studio: "Studio Pierrot",
    rating: 8.6,
    year: 2004,
    image: "images/bleach.jpg",
    description: "A teen gains Soul Reaper powers and battles evil spirits.",
  },
  {
    title: "One Piece",
    genre: "Adventure, Fantasy",
    studio: "Toei Animation",
    rating: 8.8,
    year: 1999,
    image: "images/onepiece.jpg",
    description:
      "Luffy sails the seas with his crew to find the legendary treasure.",
  },
  {
    title: "Vinland Saga",
    genre: "Action, Drama",
    studio: "Wit Studio",
    rating: 8.8,
    year: 2019,
    image: "images/vinland.jpg",
    description: "A young warrior seeks revenge during the Viking era.",
  },
  {
    title: "Demon Slayer",
    genre: "Action, Supernatural",
    studio: "ufotable",
    rating: 8.5,
    year: 2019,
    image: "images/demonslayer.jpg",
    description: "A boy joins a demon-slaying corps to avenge his family.",
  },
  {
    title: "Death Note",
    genre: "Mystery, Supernatural",
    studio: "Madhouse",
    rating: 8.6,
    year: 2006,
    image: "images/deathnote.jpg",
    description: "A high schooler gains a deadly notebook and plays god.",
  },
  {
    title: "Jujutsu Kaisen",
    genre: "Action, Fantasy",
    studio: "MAPPA",
    rating: 8.7,
    year: 2020,
    image: "images/jjk.webp",
    description: "A student battles cursed spirits with supernatural powers.",
  },
  {
    title: "My Hero Academia",
    genre: "Action, Superhero",
    studio: "Bones",
    rating: 8.0,
    year: 2016,
    image: "images/mha.jpg",
    description: "A quirkless boy trains to become the greatest hero.",
  },
  {
    title: "Hunter x Hunter",
    genre: "Adventure, Fantasy",
    studio: "Madhouse",
    rating: 8.9,
    year: 2011,
    image: "images/hxh.jpg",
    description: "Gon seeks his father and faces deadly trials as a Hunter.",
  },
  {
    title: "Mob Psycho 100",
    genre: "Action, Comedy",
    studio: "Bones",
    rating: 8.7,
    year: 2016,
    image: "images/mob.jpg",
    description: "A powerful psychic boy tries to live a normal life.",
  },
  {
    title: "One Punch Man",
    genre: "Action, Comedy",
    studio: "Madhouse",
    rating: 8.5,
    year: 2015,
    image: "images/onepunch.jpg",
    description:
      "A hero defeats enemies with a single punch—and is bored by it.",
  },
  {
    title: "JoJo's Bizarre Adventure",
    genre: "Action, Adventure",
    studio: "David Production",
    rating: 8.8,
    year: 2012,
    image: "images/jojos.jpg",
    description: "Generations of Joestars battle supernatural foes in style.",
  },
  {
    title: "Tokyo Ghoul",
    genre: "Horror, Supernatural",
    studio: "Pierrot",
    rating: 7.9,
    year: 2014,
    image: "images/tokyo.jpg",
    description:
      "A college student becomes half-ghoul and fights for identity.",
  },
  {
    title: "Naruto",
    genre: "Adventure, Ninja",
    studio: "Pierrot",
    rating: 8.3,
    year: 2002,
    image: "images/naruto.jpg",
    description: "An outcast ninja dreams of becoming the Hokage.",
  },
  {
    title: "Cowboy Bebop",
    genre: "Sci-Fi, Action",
    studio: "Sunrise",
    rating: 8.8,
    year: 1998,
    image: "images/cowboy.jpg",
    description: "Bounty hunters chase criminals across the galaxy in style.",
  },
];
