const animeCatalog = [
  {
    title: "Fullmetal Alchemist: Brotherhood",
    genre: "Action, Adventure",
    studio: "Bones",
    rating: 9.2,
    year: 2009,
    image: "images/fullmetal.jpg",
    clip: "clips/fullmetal.mp4",
    description:
      "Two brothers seek the Philosopher's Stone after a failed alchemy experiment.",
  },
  {
    title: "Attack on Titan",
    genre: "Action, Drama",
    studio: "Wit Studio / MAPPA",
    rating: 9.1,
    year: 2013,
    image: "images/aot.webp",
    clip: "clips/aot.mp4",
    description:
      "Humans fight for survival against towering man-eating titans.",
  },
  {
    title: "Bleach",
    genre: "Action, Supernatural",
    studio: "Studio Pierrot",
    rating: 8.6,
    year: 2004,
    image: "images/bleach.jpg",
    clip: "clips/bleach.mp4",
    description: "A teen gains Soul Reaper powers and battles evil spirits.",
  },
  {
    title: "One Piece",
    genre: "Adventure, Fantasy",
    studio: "Toei Animation",
    rating: 8.8,
    year: 1999,
    image: "images/onepiece.jpg",
    clip: "clips/onepiece.mp4",
    description:
      "Luffy sails the seas with his crew to find the legendary treasure.",
  },
  {
    title: "Vinland Saga",
    genre: "Action, Drama",
    studio: "Wit Studio",
    rating: 8.8,
    year: 2019,
    image: "images/vinland.jpg",
    clip: "clips/vinland.mp4",
    description: "A young warrior seeks revenge during the Viking era.",
  },
  {
    title: "Demon Slayer",
    genre: "Action, Supernatural",
    studio: "ufotable",
    rating: 8.5,
    year: 2019,
    image: "images/demonslayer.jpg",
    clip: "clips/demonslayer.mp4",
    description: "A boy joins a demon-slaying corps to avenge his family.",
  },
  {
    title: "Death Note",
    genre: "Mystery, Supernatural",
    studio: "Madhouse",
    rating: 8.6,
    year: 2006,
    image: "images/deathnote.jpg",
    clip: "clips/deathnote.mp4",
    description: "A high schooler gains a deadly notebook and plays god.",
  },
  {
    title: "Jujutsu Kaisen",
    genre: "Action, Fantasy",
    studio: "MAPPA",
    rating: 8.7,
    year: 2020,
    image: "images/jjk.webp",
    clip: "clips/jjk.mp4",
    description: "A student battles cursed spirits with supernatural powers.",
  },
  {
    title: "My Hero Academia",
    genre: "Action, Superhero",
    studio: "Bones",
    rating: 8.0,
    year: 2016,
    image: "images/mha.jpg",
    clip: "clips/mha.mp4",
    description: "A quirkless boy trains to become the greatest hero.",
  },
  {
    title: "Hunter x Hunter",
    genre: "Adventure, Fantasy",
    studio: "Madhouse",
    rating: 8.9,
    year: 2011,
    image: "images/hxh.jpg",
    clip: "clips/hxh.mp4",
    description: "Gon seeks his father and faces deadly trials as a Hunter.",
  },
  {
    title: "Mob Psycho 100",
    genre: "Action, Comedy",
    studio: "Bones",
    rating: 8.7,
    year: 2016,
    image: "images/mob.jpg",
    clip: "clips/mob.mp4",
    description: "A powerful psychic boy tries to live a normal life.",
  },
  {
    title: "One Punch Man",
    genre: "Action, Comedy",
    studio: "Madhouse",
    rating: 8.5,
    year: 2015,
    image: "images/onepunch.jpg",
    clip: "clips/onepunch.mp4",
    description:
      "A hero defeats enemies with a single punch—and is bored by it.",
  },
  {
    title: "JoJo's Bizarre Adventure",
    genre: "Action, Adventure",
    studio: "David Production",
    rating: 8.8,
    year: 2012,
    image: "images/jojos.jpg",
    clip: "clips/jojos.mp4",
    description: "Generations of Joestars battle supernatural foes in style.",
  },
  {
    title: "Tokyo Ghoul",
    genre: "Horror, Supernatural",
    studio: "Pierrot",
    rating: 7.9,
    year: 2014,
    image: "images/tokyo.jpg",
    clip: "clips/tokyo.mp4",
    description:
      "A college student becomes half-ghoul and fights for identity.",
  },
  {
    title: "Naruto",
    genre: "Adventure, Ninja",
    studio: "Pierrot",
    rating: 8.3,
    year: 2002,
    image: "images/naruto.jpg",
    clip: "clips/naruto.mp4",
    description: "An outcast ninja dreams of becoming the Hokage.",
  },
  {
    title: "Cyberpunk: Edgerunners",
    genre: "Sci-Fi, Action",
    studio: "Trigger",
    rating: 8.5,
    year: 2022,
    image: "images/edgerunners.jpg",
    clip: "clips/edgerunners.mp4",
    description:
      "A street kid becomes an Edgerunner in a tech-dystopian world.",
  },
  {
    title: "86",
    genre: "Sci-Fi, Drama",
    studio: "A-1 Pictures",
    rating: 8.3,
    year: 2021,
    image: "images/86.jpg",
    clip: "clips/86.mp4",
    description:
      "A war is fought by unmanned drones—except they're not really unmanned.",
  },
  {
    title: "Re:Zero - Starting Life in Another World",
    genre: "Fantasy, Drama",
    studio: "White Fox",
    rating: 8.1,
    year: 2016,
    image: "images/rezero.jpg",
    clip: "clips/rezero.mp4",
    description:
      "A boy is transported to a fantasy world and trapped in a time loop.",
  },
  {
    title: "Solo Leveling",
    genre: "Action, Fantasy",
    studio: "A-1 Pictures",
    rating: 8.7,
    year: 2024,
    image: "images/sololeveling.jpg",
    clip: "clips/sololeveling.mp4",
    description:
      "A weak hunter becomes the world’s strongest through a system.",
  },
  {
    title: "Dandadan",
    genre: "Supernatural, Comedy",
    studio: "Science SARU",
    rating: 8.2,
    year: 2024,
    image: "images/dandadan.jpg",
    clip: "clips/dandadan.mp4",
    description:
      "Two teens dive into bizarre battles involving ghosts and aliens.",
  },
  {
    title: "Sakamoto Days",
    genre: "Action, Comedy",
    studio: "TMS Entertainment",
    rating: 8.3,
    year: 2025,
    image: "images/sakamoto.jpg",
    clip: "clips/sakamoto.mp4",
    description:
      "A retired hitman turned family man is dragged back into action.",
  },
  {
    title: "Kaiju No. 8",
    genre: "Action, Sci-Fi",
    studio: "Production I.G",
    rating: 8.4,
    year: 2024,
    image: "images/kaiju8.jpg",
    clip: "clips/kaiju8.mp4",
    description:
      "A monster cleanup worker gains kaiju powers and fights for humanity.",
  },
  {
    title: "Cowboy Bebop",
    genre: "Sci-Fi, Action",
    studio: "Sunrise",
    rating: 8.8,
    year: 1998,
    image: "images/cowboy.jpg",
    clip: "clips/cowboy.mp4",
    description: "Bounty hunters chase criminals across the galaxy in style.",
  },
  {
    title: "Code Geass",
    genre: "Mecha, Drama",
    studio: "Sunrise",
    rating: 8.9,
    year: 2006,
    image: "images/codegeass.jpg",
    clip: "clips/codegeass.mp4",
    description: "A prince with a mysterious power rebels against an empire.",
  },
  {
    title: "Steins;Gate",
    genre: "Sci-Fi, Thriller",
    studio: "White Fox",
    rating: 9.1,
    year: 2011,
    image: "images/steinsgate.jpg",
    clip: "clips/steinsgate.mp4",
    description: "A scientist discovers time travel with dire consequences.",
  },
  {
    title: "Erased",
    genre: "Mystery, Drama",
    studio: "A-1 Pictures",
    rating: 8.5,
    year: 2016,
    image: "images/erased.jpg",
    clip: "clips/erased.mp4",
    description: "A man travels back in time to prevent a tragedy.",
  },
  {
    title: "Parasyte: The Maxim",
    genre: "Horror, Action",
    studio: "Madhouse",
    rating: 8.4,
    year: 2014,
    image: "images/parasyte.jpg",
    clip: "clips/parasyte.mp4",
    description: "A teen fights alien parasites that take over human bodies.",
  },
  {
    title: "Your Lie in April",
    genre: "Romance, Drama",
    studio: "A-1 Pictures",
    rating: 8.6,
    year: 2014,
    image: "images/yourlie.jpg",
    clip: "clips/yourlie.mp4",
    description: "A pianist rediscovers music and emotion through love.",
  },
  {
    title: "Toradora!",
    genre: "Romance, Comedy",
    studio: "J.C.Staff",
    rating: 8.0,
    year: 2008,
    image: "images/toradora.jpg",
    clip: "clips/toradora.mp4",
    description: "Two classmates team up to help each other find love.",
  },
  {
    title: "The Promised Neverland",
    genre: "Mystery, Horror",
    studio: "CloverWorks",
    rating: 8.4,
    year: 2019,
    image: "images/neverland.jpg",
    clip: "clips/neverland.mp4",
    description: "Children uncover a dark secret and plot their escape.",
  },
  {
    title: "Dr. Stone",
    genre: "Sci-Fi, Adventure",
    studio: "TMS Entertainment",
    rating: 8.2,
    year: 2019,
    image: "images/drstone.jpg",
    clip: "clips/drstone.mp4",
    description:
      "A genius teen rebuilds civilization after humanity turns to stone.",
  },
  {
    title: "Black Clover",
    genre: "Fantasy, Action",
    studio: "Studio Pierrot",
    rating: 8.1,
    year: 2017,
    image: "images/blackclover.jpg",
    clip: "clips/blackclover.mp4",
    description: "A boy with no magic strives to become the Wizard King.",
  },
  {
    title: "Spy x Family",
    genre: "Comedy, Action",
    studio: "Wit Studio / CloverWorks",
    rating: 8.6,
    year: 2022,
    image: "images/spyxfamily.jpg",
    clip: "clips/spyxfamily.mp4",
    description: "A spy builds a fake family—unaware of their hidden talents.",
  },
  {
    title: "Neon Genesis Evangelion",
    genre: "Mecha, Psychological",
    studio: "Gainax",
    rating: 8.5,
    year: 1995,
    image: "images/evangelion.jpg",
    clip: "clips/evangelion.mp4",
    description:
      "Teens pilot giant mechs to defend humanity from mysterious beings.",
  },
  {
    title: "Fate/Zero",
    genre: "Action, Supernatural",
    studio: "ufotable",
    rating: 8.7,
    year: 2011,
    image: "images/fatezero.jpg",
    clip: "clips/fatezero.mp4",
    description:
      "Seven mages summon legendary heroes to fight for the Holy Grail.",
  },
  {
    title: "Sword Art Online",
    genre: "Action, Adventure",
    studio: "A-1 Pictures",
    rating: 7.8,
    year: 2012,
    image: "images/sao.jpg",
    clip: "clips/sao.mp4",
    description:
      "Players are trapped in a virtual reality game and must clear it to escape.",
  },
  {
    title: "Chainsaw Man",
    genre: "Action, Supernatural",
    studio: "MAPPA",
    rating: 8.7,
    year: 2022,
    image: "images/chainsawman.jpg",
    clip: "clips/chainsawman.mp4",
    description:
      "A boy with chainsaw powers hunts devils to pay off his debts.",
  },
  {
    title: "Blue Lock",
    genre: "Sports, Drama",
    studio: "8bit",
    rating: 8.4,
    year: 2022,
    image: "images/bluelock.jpg",
    clip: "clips/bluelock.mp4",
    description: "Strikers compete in a high-stakes soccer training program.",
  },
  {
    title: "Oshi no Ko",
    genre: "Drama, Mystery",
    studio: "Doga Kobo",
    rating: 8.9,
    year: 2023,
    image: "images/oshinoko.jpg",
    clip: "clips/oshinoko.mp4",
    description:
      "A reincarnated doctor uncovers the dark side of the idol industry.",
  },
  {
    title: "The Rising of the Shield Hero",
    genre: "Fantasy, Adventure",
    studio: "Kinema Citrus",
    rating: 8.0,
    year: 2019,
    image: "images/shieldhero.jpg",
    clip: "clips/shieldhero.mp4",
    description: "A man summoned to another world becomes the Shield Hero.",
  },
  {
    title: "Made in Abyss",
    genre: "Adventure, Fantasy",
    studio: "Kinema Citrus",
    rating: 8.8,
    year: 2017,
    image: "images/madeinabyss.jpg",
    clip: "clips/madeinabyss.mp4",
    description: "A girl and a robot explore a mysterious, dangerous abyss.",
  },
  {
    title: "Noragami",
    genre: "Action, Supernatural",
    studio: "Bones",
    rating: 8.2,
    year: 2014,
    image: "images/noragami.jpg",
    clip: "clips/noragami.mp4",
    description: "A minor god seeks recognition by helping humans in need.",
  },
  {
    title: "Akame ga Kill!",
    genre: "Action, Fantasy",
    studio: "White Fox",
    rating: 7.8,
    year: 2014,
    image: "images/akamegakill.jpg",
    clip: "clips/akamegakill.mp4",
    description: "A boy joins an assassin group to fight a corrupt empire.",
  },
  {
    title: "Kaguya-sama: Love is War",
    genre: "Romance, Comedy",
    studio: "A-1 Pictures",
    rating: 8.9,
    year: 2019,
    image: "images/kaguya.jpg",
    clip: "clips/kaguya.mp4",
    description:
      "Two student council members battle to make the other confess love first.",
  },
  {
    title: "Clannad: After Story",
    genre: "Drama, Romance",
    studio: "Kyoto Animation",
    rating: 9.0,
    year: 2008,
    image: "images/clannad.jpg",
    clip: "clips/clannad.mp4",
    description: "A young couple faces the challenges of adulthood and family.",
  },
  {
    title: "Hellsing Ultimate",
    genre: "Action, Horror",
    studio: "Madhouse",
    rating: 8.3,
    year: 2006,
    image: "images/hellsing.jpg",
    clip: "clips/hellsing.mp4",
    description:
      "A vampire works for an organization to protect England from supernatural threats.",
  },
  {
    title: "Berserk (1997)",
    genre: "Action, Dark Fantasy",
    studio: "OLM",
    rating: 8.7,
    year: 1997,
    image: "images/berserk.jpg",
    clip: "clips/berserk.mp4",
    description: "A mercenary fights for survival in a brutal medieval world.",
  },
  {
    title: "Monster",
    genre: "Mystery, Thriller",
    studio: "Madhouse",
    rating: 9.0,
    year: 2004,
    image: "images/monster.jpg",
    clip: "clips/monster.mp4",
    description: "A doctor hunts a serial killer whose life he once saved.",
  },
  {
    title: "Vivy: Fluorite Eye's Song",
    genre: "Sci-Fi, Action",
    studio: "Wit Studio",
    rating: 8.5,
    year: 2021,
    image: "images/vivy.jpg",
    clip: "clips/vivy.mp4",
    description:
      "An AI singer fights to prevent a future war between humans and machines.",
  },
  {
    title: "Ergo Proxy",
    genre: "Sci-Fi, Mystery",
    studio: "Manglobe",
    rating: 8.0,
    year: 2006,
    image: "images/ergoproxy.jpg",
    clip: "clips/ergoproxy.mp4",
    description: "A detective investigates murders in a dystopian future.",
  },
  {
    title: "The Devil is a Part-Timer!",
    genre: "Comedy, Fantasy",
    studio: "White Fox",
    rating: 7.8,
    year: 2013,
    image: "images/devilparttimer.jpg",
    clip: "clips/devilparttimer.mp4",
    description:
      "A demon lord works at a fast-food restaurant in modern Tokyo.",
  },
  {
    title: "Horimiya",
    genre: "Romance, Slice of Life",
    studio: "CloverWorks",
    rating: 8.2,
    year: 2021,
    image: "images/horimiya.jpg",
    clip: "clips/horimiya.mp4",
    description: "Two high schoolers bond over their hidden personalities.",
  },
  {
    title: "ReLIFE",
    genre: "Romance, Drama",
    studio: "TMS Entertainment",
    rating: 8.0,
    year: 2016,
    image: "images/relife.jpg",
    clip: "clips/relife.mp4",
    description: "A man gets a second chance at life by reliving high school.",
  },
  {
    title: "Gintama",
    genre: "Action, Comedy",
    studio: "Sunrise",
    rating: 9.0,
    year: 2006,
    image: "images/gintama.jpg",
    clip: "clips/gintama.mp4",
    description:
      "A samurai and his friends take odd jobs in an alien-ruled Edo.",
  },

  {
    title: "Psycho-Pass",
    genre: "Sci-Fi, Thriller",
    studio: "Production I.G",
    rating: 8.4,
    year: 2012,
    image: "images/psychopass.jpg",
    clip: "clips/psychopass.mp4",
    description:
      "In a dystopian future, crimes are prevented before they happen.",
  },
];
